import type { File, Category } from '@/types';

export const CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Work Documents', color: '#3B5998' },
  { id: 'cat-2', name: 'Personal Photos', color: '#008080' },
  { id: 'cat-3', name: 'Project Blueprints', color: '#8A2BE2' },
  { id: 'cat-4', name: 'Invoices', color: '#FF4500' },
  { id: 'cat-5', name: 'Archived Records', color: '#708090' },
];

export const FILES: File[] = [
  {
    id: 'file-1',
    name: 'Q4_Financial_Report.pdf',
    size: '1.2 MB',
    uploadedAt: '2024-07-22T14:30:00Z',
    category: CATEGORIES[0],
    tags: ['finance', 'report', 'quarterly'],
    type: 'document',
  },
  {
    id: 'file-2',
    name: 'summer_vacation_01.jpg',
    size: '4.5 MB',
    uploadedAt: '2024-07-22T10:15:00Z',
    category: CATEGORIES[1],
    tags: ['vacation', 'beach', 'summer'],
    type: 'image',
  },
  {
    id: 'file-3',
    name: 'Project_Alpha_Architecture.dwg',
    size: '15.8 MB',
    uploadedAt: '2024-07-21T18:00:00Z',
    category: CATEGORIES[2],
    tags: ['architecture', 'cad', 'blueprint'],
    type: 'document',
  },
  {
    id: 'file-4',
    name: 'Invoice_INV-00123.pdf',
    size: '88 KB',
    uploadedAt: '2024-07-21T09:05:00Z',
    category: CATEGORIES[3],
    tags: ['billing', 'client-x', 'payment'],
    type: 'document',
  },
    {
    id: 'file-5',
    name: 'Old_Client_Contract.docx',
    size: '256 KB',
    uploadedAt: '2023-01-15T11:45:00Z',
    category: CATEGORIES[4],
    tags: ['contract', 'legal', 'archive'],
    type: 'document',
  },
  {
    id: 'file-6',
    name: 'company_logo_final.png',
    size: '312 KB',
    uploadedAt: '2023-01-14T16:20:00Z',
    category: CATEGORIES[0],
    tags: ['branding', 'logo', 'design'],
    type: 'image',
  },
  {
    id: 'file-7',
    name: 'Team_Meeting_Notes.mp3',
    size: '22.1 MB',
    uploadedAt: '2024-06-15T11:00:00Z',
    category: CATEGORIES[0],
    tags: ['meeting', 'audio', 'internal'],
    type: 'audio',
  },
  {
    id: 'file-8',
    name: 'Holiday_Party_2023.mp4',
    size: '1.2 GB',
    uploadedAt: '2023-12-20T21:00:00Z',
    category: CATEGORIES[1],
    tags: ['event', 'video', 'team'],
    type: 'video',
  },
  {
    id: 'file-9',
    name: 'Invoice_Vendor_XYZ.pdf',
    size: '95 KB',
    uploadedAt: '2024-05-30T10:00:00Z',
    category: CATEGORIES[3],
    tags: ['invoice', 'vendor', 'expense'],
    type: 'document',
  },
  {
    id: 'file-10',
    name: 'Website_Redesign_Mockup.fig',
    size: '7.2 MB',
    uploadedAt: '2024-04-10T15:20:00Z',
    category: CATEGORIES[2],
    tags: ['design', 'mockup', 'website'],
    type: 'other',
  },
  {
    id: 'file-11',
    name: 'Archived_Emails_2022.zip',
    size: '150 MB',
    uploadedAt: '2023-01-05T09:00:00Z',
    category: CATEGORIES[4],
    tags: ['archive', 'email', 'backup'],
    type: 'other',
  },
  {
    id: 'file-12',
    name: 'Family_Reunion_Photo.jpg',
    size: '5.1 MB',
    uploadedAt: '2023-08-12T13:45:00Z',
    category: CATEGORIES[1],
    tags: ['family', 'photo', 'event'],
    type: 'image',
  },
  {
    id: 'file-13',
    name: 'Marketing_Campaign_Plan.docx',
    size: '450 KB',
    uploadedAt: '2024-03-01T14:00:00Z',
    category: CATEGORIES[0],
    tags: ['marketing', 'plan', 'strategy'],
    type: 'document',
  },
  {
    id: 'file-14',
    name: 'Building_Permit_Scan.pdf',
    size: '3.3 MB',
    uploadedAt: '2023-11-22T08:30:00Z',
    category: CATEGORIES[2],
    tags: ['permit', 'legal', 'construction'],
    type: 'document',
  },
  {
    id: 'file-15',
    name: 'Utility_Bill_May.pdf',
    size: '70 KB',
    uploadedAt: '2024-06-05T17:10:00Z',
    category: CATEGORIES[3],
    tags: ['bill', 'utilities', 'invoice'],
    type: 'document',
  },
  {
    id: 'file-16',
    name: 'Concert_Clip.mov',
    size: '58 MB',
    uploadedAt: '2023-09-18T22:45:00Z',
    category: CATEGORIES[1],
    tags: ['concert', 'music', 'video'],
    type: 'video',
  },
  {
    id: 'file-17',
    name: 'HR_Policy_Update.pdf',
    size: '750 KB',
    uploadedAt: '2024-02-15T16:00:00Z',
    category: CATEGORIES[0],
    tags: ['hr', 'policy', 'document'],
    type: 'document',
  },
  {
    id: 'file-18',
    name: 'Historical_Record_Scan.tiff',
    size: '25 MB',
    uploadedAt: '2022-06-10T12:00:00Z',
    category: CATEGORIES[4],
    tags: ['archive', 'history', 'scan'],
    type: 'image',
  },
];
