import type { File, Category } from '@/types';

export const CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Documentos de Trabajo', color: '#3B5998' },
  { id: 'cat-2', name: 'Fotos Personales', color: '#008080' },
  { id: 'cat-3', name: 'Planos de Proyecto', color: '#8A2BE2' },
  { id: 'cat-4', name: 'Facturas', color: '#FF4500' },
  { id: 'cat-5', name: 'Registros Archivados', color: '#708090' },
];

export const FILES: File[] = [
  {
    id: 'file-1',
    name: 'Q4_Financial_Report.pdf',
    size: '1.2 MB',
    uploadedAt: '2024-07-22T14:30:00Z',
    category: CATEGORIES[0],
    tags: ['finanzas', 'reporte', 'trimestral'],
    type: 'document',
  },
  {
    id: 'file-2',
    name: 'vacaciones_verano_01.jpg',
    size: '4.5 MB',
    uploadedAt: '2024-07-22T10:15:00Z',
    category: CATEGORIES[1],
    tags: ['vacaciones', 'playa', 'verano'],
    type: 'image',
  },
  {
    id: 'file-3',
    name: 'Proyecto_Alpha_Arquitectura.dwg',
    size: '15.8 MB',
    uploadedAt: '2024-07-21T18:00:00Z',
    category: CATEGORIES[2],
    tags: ['arquitectura', 'cad', 'plano'],
    type: 'document',
  },
  {
    id: 'file-4',
    name: 'Factura_INV-00123.pdf',
    size: '88 KB',
    uploadedAt: '2024-07-21T09:05:00Z',
    category: CATEGORIES[3],
    tags: ['facturación', 'cliente-x', 'pago'],
    type: 'document',
  },
    {
    id: 'file-5',
    name: 'Contrato_Antiguo_Cliente.docx',
    size: '256 KB',
    uploadedAt: '2023-01-15T11:45:00Z',
    category: CATEGORIES[4],
    tags: ['contrato', 'legal', 'archivo'],
    type: 'document',
  },
  {
    id: 'file-6',
    name: 'logo_empresa_final.png',
    size: '312 KB',
    uploadedAt: '2023-01-14T16:20:00Z',
    category: CATEGORIES[0],
    tags: ['branding', 'logo', 'diseño'],
    type: 'image',
  },
  {
    id: 'file-7',
    name: 'Notas_Reunion_Equipo.mp3',
    size: '22.1 MB',
    uploadedAt: '2024-06-15T11:00:00Z',
    category: CATEGORIES[0],
    tags: ['reunión', 'audio', 'interno'],
    type: 'audio',
  },
  {
    id: 'file-8',
    name: 'Fiesta_Navidad_2023.mp4',
    size: '1.2 GB',
    uploadedAt: '2023-12-20T21:00:00Z',
    category: CATEGORIES[1],
    tags: ['evento', 'video', 'equipo'],
    type: 'video',
  },
  {
    id: 'file-9',
    name: 'Factura_Proveedor_XYZ.pdf',
    size: '95 KB',
    uploadedAt: '2024-05-30T10:00:00Z',
    category: CATEGORIES[3],
    tags: ['factura', 'proveedor', 'gasto'],
    type: 'document',
  },
  {
    id: 'file-10',
    name: 'Mockup_Rediseño_Web.fig',
    size: '7.2 MB',
    uploadedAt: '2024-04-10T15:20:00Z',
    category: CATEGORIES[2],
    tags: ['diseño', 'mockup', 'web'],
    type: 'other',
  },
  {
    id: 'file-11',
    name: 'Emails_Archivados_2022.zip',
    size: '150 MB',
    uploadedAt: '2023-01-05T09:00:00Z',
    category: CATEGORIES[4],
    tags: ['archivo', 'email', 'backup'],
    type: 'other',
  },
  {
    id: 'file-12',
    name: 'Foto_Reunion_Familiar.jpg',
    size: '5.1 MB',
    uploadedAt: '2023-08-12T13:45:00Z',
    category: CATEGORIES[1],
    tags: ['familia', 'foto', 'evento'],
    type: 'image',
  },
  {
    id: 'file-13',
    name: 'Plan_Campaña_Marketing.docx',
    size: '450 KB',
    uploadedAt: '2024-03-01T14:00:00Z',
    category: CATEGORIES[0],
    tags: ['marketing', 'plan', 'estrategia'],
    type: 'document',
  },
  {
    id: 'file-14',
    name: 'Permiso_Construccion_Scan.pdf',
    size: '3.3 MB',
    uploadedAt: '2023-11-22T08:30:00Z',
    category: CATEGORIES[2],
    tags: ['permiso', 'legal', 'construcción'],
    type: 'document',
  },
  {
    id: 'file-15',
    name: 'Factura_Servicios_Mayo.pdf',
    size: '70 KB',
    uploadedAt: '2024-06-05T17:10:00Z',
    category: CATEGORIES[3],
    tags: ['factura', 'servicios', 'recibo'],
    type: 'document',
  },
  {
    id: 'file-16',
    name: 'Clip_Concierto.mov',
    size: '58 MB',
    uploadedAt: '2023-09-18T22:45:00Z',
    category: CATEGORIES[1],
    tags: ['concierto', 'musica', 'video'],
    type: 'video',
  },
  {
    id: 'file-17',
    name: 'Actualizacion_Politica_RRHH.pdf',
    size: '750 KB',
    uploadedAt: '2024-02-15T16:00:00Z',
    category: CATEGORIES[0],
    tags: ['rrhh', 'política', 'documento'],
    type: 'document',
  },
  {
    id: 'file-18',
    name: 'Registro_Historico_Scan.tiff',
    size: '25 MB',
    uploadedAt: '2022-06-10T12:00:00Z',
    category: CATEGORIES[4],
    tags: ['archivo', 'historia', 'scan'],
    type: 'image',
  },
];
