import type { File, Category } from '@/types';

export const CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Estudios de Impacto (EIA)', color: '#3B5998' },
  { id: 'cat-2', name: 'Inspecciones de Obra', color: '#008080' },
  { id: 'cat-3', name: 'Informes de Seguimiento', color: '#8A2BE2' },
  { id: 'cat-4', name: 'Documentación Legal', color: '#FF4500' },
  { id: 'cat-5', name: 'Planos y Cartografía', color: '#708090' },
];

export const FILES: File[] = [
  {
    id: 'file-1',
    name: 'EIA_Canal_Aliviador_Sur.pdf',
    size: '25.3 MB',
    uploadedAt: '2024-07-22T14:30:00Z',
    category: CATEGORIES[0],
    tags: ['eia', 'hidráulica', 'rural'],
    type: 'document',
  },
  {
    id: 'file-2',
    name: 'Fotos_Inspeccion_Defensa_Costera.zip',
    size: '150.2 MB',
    uploadedAt: '2024-07-22T10:15:00Z',
    category: CATEGORIES[1],
    tags: ['inspección', 'fotografía', 'costa'],
    type: 'image',
  },
  {
    id: 'file-3',
    name: 'Seguimiento_Presa_El_Mollar_Q2.pdf',
    size: '2.1 MB',
    uploadedAt: '2024-07-21T18:00:00Z',
    category: CATEGORIES[2],
    tags: ['seguimiento', 'presa', 'monitoreo'],
    type: 'document',
  },
  {
    id: 'file-4',
    name: 'Resolucion_Aprobacion_045-22.pdf',
    size: '88 KB',
    uploadedAt: '2024-07-21T09:05:00Z',
    category: CATEGORIES[3],
    tags: ['resolución', 'legal', 'aprobación'],
    type: 'document',
  },
    {
    id: 'file-5',
    name: 'Plano_Desague_Urbano_Centro.dwg',
    size: '32.5 MB',
    uploadedAt: '2023-01-15T11:45:00Z',
    category: CATEGORIES[4],
    tags: ['plano', 'autocad', 'urbano'],
    type: 'document',
  },
  {
    id: 'file-6',
    name: 'Minuta_Reunion_Comite_Cuenca.docx',
    size: '312 KB',
    uploadedAt: '2023-01-14T16:20:00Z',
    category: CATEGORIES[0],
    tags: ['minuta', 'reunión', 'cuenca'],
    type: 'document',
  },
  {
    id: 'file-7',
    name: 'Audio_Audiencia_Publica_Canal_Norte.mp3',
    size: '88.4 MB',
    uploadedAt: '2024-06-15T11:00:00Z',
    category: CATEGORIES[0],
    tags: ['audiencia', 'audio', 'pública'],
    type: 'audio',
  },
  {
    id: 'file-8',
    name: 'Video_Vuelo_Dron_Obra_Defensa_Sur.mp4',
    size: '1.2 GB',
    uploadedAt: '2023-12-20T21:00:00Z',
    category: CATEGORIES[1],
    tags: ['inspección', 'video', 'dron'],
    type: 'video',
  },
  {
    id: 'file-9',
    name: 'Informe_Monitoreo_Calidad_Agua_Q1.pdf',
    size: '4.5 MB',
    uploadedAt: '2024-05-30T10:00:00Z',
    category: CATEGORIES[2],
    tags: ['monitoreo', 'agua', 'calidad'],
    type: 'document',
  },
  {
    id: 'file-10',
    name: 'Mapa_Cuenca_Afectada.kml',
    size: '1.2 MB',
    uploadedAt: '2024-04-10T15:20:00Z',
    category: CATEGORIES[4],
    tags: ['mapa', 'cartografía', 'gis'],
    type: 'other',
  },
  {
    id: 'file-11',
    name: 'Licitacion_Publica_05-2022.zip',
    size: '55.6 MB',
    uploadedAt: '2023-01-05T09:00:00Z',
    category: CATEGORIES[3],
    tags: ['licitación', 'legal', 'archivo'],
    type: 'other',
  },
  {
    id: 'file-12',
    name: 'Foto_Area_Inundable_Pre_Obra.jpg',
    size: '5.1 MB',
    uploadedAt: '2023-08-12T13:45:00Z',
    category: CATEGORIES[1],
    tags: ['fotografía', 'inspección', 'diagnóstico'],
    type: 'image',
  },
  {
    id: 'file-13',
    name: 'Estudio_Hidrologico_Rio_Lules.pdf',
    size: '12.8 MB',
    uploadedAt: '2024-03-01T14:00:00Z',
    category: CATEGORIES[0],
    tags: ['eia', 'hidrología', 'estudio'],
    type: 'document',
  },
  {
    id: 'file-14',
    name: 'Certificado_Aptitud_Ambiental.pdf',
    size: '1.3 MB',
    uploadedAt: '2023-11-22T08:30:00Z',
    category: CATEGORIES[3],
    tags: ['certificado', 'legal', 'ambiental'],
    type: 'document',
  },
  {
    id: 'file-15',
    name: 'Informe_Avance_Obra_Junio.pdf',
    size: '7.8 MB',
    uploadedAt: '2024-06-05T17:10:00Z',
    category: CATEGORIES[2],
    tags: ['seguimiento', 'avance', 'obra'],
    type: 'document',
  },
  {
    id: 'file-16',
    name: 'Clip_Testimonio_Vecinal.mov',
    size: '58 MB',
    uploadedAt: '2023-09-18T22:45:00Z',
    category: CATEGORIES[0],
    tags: ['audiencia', 'video', 'testimonio'],
    type: 'video',
  },
  {
    id: 'file-17',
    name: 'Manual_Buenas_Practicas_Ambientales.pdf',
    size: '750 KB',
    uploadedAt: '2024-02-15T16:00:00Z',
    category: CATEGORIES[0],
    tags: ['manual', 'ambiental', 'guía'],
    type: 'document',
  },
  {
    id: 'file-18',
    name: 'Plano_Historico_Catastro_1985.tiff',
    size: '25 MB',
    uploadedAt: '2022-06-10T12:00:00Z',
    category: CATEGORIES[4],
    tags: ['plano', 'histórico', 'catastro'],
    type: 'image',
  },
];
