import type { Category, Milestone } from '@/types';

// NOTE: This category object is a placeholder. The actual, state-managed category
// object from `src/lib/data.ts` will be mapped in the component.
const otrosCategory: Category = { id: 'cat-otros', name: 'Otros', color: '#888888' };

const parseDate = (dateStr: string): string => {
    const [day, month, year] = dateStr.split('/');
    // Set time to 12:00:00 UTC to avoid timezone shifts affecting the date.
    const date = new Date(Date.UTC(Number(year), Number(month) - 1, Number(day), 12, 0, 0));
    return date.toISOString();
};

const createDescription = (avance: string | null, documento: string | null): string => {
    const parts = [];
    if (avance) parts.push(`Avance: ${avance}%.`);
    if (documento) parts.push(`Documento: ${documento}`);
    if (parts.length === 0) return 'No hay detalles adicionales.';
    return parts.join(' ');
};

export const RSB002_MILESTONES: Milestone[] = [
  {
    id: 'rsb002-1',
    name: 'PGA para ETP entregado (marzo 2023)',
    description: createDescription(null, null),
    occurredAt: parseDate('22/03/2023'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-2',
    name: 'EIA se envia al Ministerio de Ambiente',
    description: createDescription(null, 'EX-2023-18048409- GDEBA - DPTLMIYSPGP'),
    occurredAt: parseDate('08/05/2023'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-3',
    name: 'PGA aprobado',
    description: createDescription(null, 'EX-2023-14083060-GDEBA-DPTLMIYSPGP'),
    occurredAt: parseDate('22/10/2020'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-4',
    name: 'Reenvio PGA',
    description: createDescription(null, 'IF-2024-33196627-GDEBA-DPTLMIYSPGP'),
    occurredAt: parseDate('17/09/2024'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-5',
    name: 'PGA desaprobado',
    description: createDescription(null, 'PV-2024-37721056-GDEBA-DTPMIYSPGP'),
    occurredAt: parseDate('24/10/2024'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-6',
    name: 'PGA aprobado',
    description: createDescription(null, 'EX-2025-01923658--GDEBA-DPTLMIYSPGP'),
    occurredAt: parseDate('21/11/2024'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-7',
    name: 'Anexo I',
    description: createDescription(null, 'IF-2025-01924871-GDEBA-DEDPOHMIYSPGP'),
    occurredAt: parseDate('02/12/2024'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-8',
    name: 'IIMS noviembre 2024',
    description: createDescription(null, 'IF-2025-01924500-GDEBA-DEDPOHMIYSPGP'),
    occurredAt: parseDate('16/01/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-9',
    name: 'IF-2025-08040640-GDEBA-DEDPOHMIYSPGP',
    description: createDescription(null, 'IF-2025-01924871-GDEBA-DEDPOHMIYSPGP'),
    occurredAt: parseDate('16/01/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-10',
    name: 'IMS desaprobado dic 2024',
    description: createDescription(null, 'PV-2025-02475898-GDEBA-DTPMIYSPGP'),
    occurredAt: parseDate('22/01/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-11',
    name: 'rta IMS nov-dic 24',
    description: createDescription(null, 'PV-2025-03808076-GDEBA-DTPMIYSPGP'),
    occurredAt: parseDate('03/02/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-12',
    name: 'IMS Ddiciembre 2024',
    description: createDescription('7,5', 'IF-2025-08040640-GDEBA-DEDPOHMIYSPGP'),
    occurredAt: parseDate('11/03/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-13',
    name: 'IMS Enero 2025',
    description: createDescription('13,59', 'IF-2025-08041467-GDEBA-DEDPOHMIYSPGP'),
    occurredAt: parseDate('11/03/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-14',
    name: 'IMS Febrero 2025',
    description: createDescription('16', 'IF-2025-08041906-GDEBA-DEDPOHMIYSPGP'),
    occurredAt: parseDate('11/03/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-15',
    name: 'Aprobado IMS dic-ene feb 25',
    description: createDescription(null, 'PV-2025-11620652-GDEBA-DTPMIYSPGP'),
    occurredAt: parseDate('04/04/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-16',
    name: 'IMS marzo 2025',
    description: createDescription('17,5', 'IF-2025-14968849-GDEBA-DEDPOHMIYSPGP'),
    occurredAt: parseDate('05/05/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-17',
    name: 'IMS abril 2025',
    description: createDescription('19,5', 'IF-2025-14969204-GDEBA-DEDPOHMIYSPGP'),
    occurredAt: parseDate('05/05/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
  {
    id: 'rsb002-18',
    name: 'IMS mayo 2025',
    description: createDescription('21', 'IF-2025-19351037-GDEBA-DEDPOHMIYSPGP'),
    occurredAt: parseDate('03/06/2025'),
    category: otrosCategory,
    tags: null,
    associatedFiles: [],
    isImportant: false,
    history: ['Hito creado a partir de tabla de datos.'],
  },
];
