import type { Milestone } from '@/types';
import { CATEGORIES } from '@/lib/data';

export const SAMPLE_MILESTONES: Milestone[] = [
  {
    id: 'sample-1',
    name: 'RSA060 - Adjudicación del Contrato',
    description: 'Firma del contrato con la UTE constructora para el inicio de las obras del proyecto RSA060.',
    occurredAt: '2022-07-26T12:00:00.000Z',
    category: CATEGORIES[3],
    tags: ['contrato', 'legal', 'adjudicación'],
    associatedFiles: [{ id: 'f1', name: 'contrato_RSA060.pdf', size: '5.4 MB', type: 'document' }],
    isImportant: true,
    history: ['2022-07-26T12:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-2',
    name: 'RSA060 - Movilización Inicial de Equipos',
    description: 'Llegada de la primera maquinaria pesada al sitio de la obra y montaje del campamento.',
    occurredAt: '2022-08-15T09:30:00.000Z',
    category: CATEGORIES[1],
    tags: ['maquinaria', 'logística', 'inicio'],
    associatedFiles: [{ id: 'f2', name: 'reporte_movilizacion.pdf', size: '850 KB', type: 'document' }],
    isImportant: false,
    history: ['2022-08-15T09:30:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-3',
    name: 'RSA060 - Reunión de Inicio con Contratista',
    description: 'Primera reunión oficial en obra para coordinar las primeras tareas y protocolos de seguridad.',
    occurredAt: '2022-08-20T11:00:00.000Z',
    category: CATEGORIES[5],
    tags: ['reunión', 'kick-off', 'seguridad'],
    associatedFiles: [{ id: 'f3', name: 'minuta_reunion_001.pdf', size: '320 KB', type: 'document' }],
    isImportant: false,
    history: ['2022-08-20T11:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-4',
    name: 'RSA060 - Aprobación del Estudio de Suelos',
    description: 'Se reciben y aprueban los resultados del estudio geotécnico para la fundación de la presa.',
    occurredAt: '2022-09-14T14:00:00.000Z',
    category: CATEGORIES[0],
    tags: ['geotecnia', 'suelos', 'eia'],
    associatedFiles: [{ id: 'f4', name: 'informe_geotecnico_final.pdf', size: '12.1 MB', type: 'document' }],
    isImportant: true,
    history: ['2022-09-14T14:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-5',
    name: 'RSA060 - Primer Despeje y Nivelación',
    description: 'Inspección del inicio de los trabajos de despeje del terreno en el área de la presa.',
    occurredAt: '2022-09-24T08:00:00.000Z',
    category: CATEGORIES[1],
    tags: ['despeje', 'topografía', 'obra'],
    associatedFiles: [{ id: 'f5', name: 'fotos_despeje_01.zip', size: '25 MB', type: 'image' }],
    isImportant: false,
    history: ['2022-09-24T08:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-6',
    name: 'RSA060 - Presentación Planos de Detalle',
    description: 'El contratista presenta la primera tanda de planos de detalle para la estructura de hormigón.',
    occurredAt: '2022-10-14T15:00:00.000Z',
    category: CATEGORIES[4],
    tags: ['planos', 'ingeniería', 'hormigón'],
    associatedFiles: [{ id: 'f6', name: 'RSA060-EST-001-A.dwg', size: '8.9 MB', type: 'other' }],
    isImportant: false,
    history: ['2022-10-14T15:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-7',
    name: 'RSA060 - Informe de Seguimiento Ambiental Q3 2022',
    description: 'Primer informe trimestral sobre el monitoreo de fauna y flora durante el despeje.',
    occurredAt: '2022-11-13T10:00:00.000Z',
    category: CATEGORIES[2],
    tags: ['seguimiento', 'ambiental', 'fauna'],
    associatedFiles: [{ id: 'f7', name: 'informe_ambiental_Q3_22.pdf', size: '2.5 MB', type: 'document' }],
    isImportant: false,
    history: ['2022-11-13T10:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-8',
    name: 'RSA060 - Inicio de Excavaciones del Aliviadero',
    description: 'Inspección visual del comienzo de las excavaciones para el canal del aliviadero de la presa.',
    occurredAt: '2022-12-03T09:00:00.000Z',
    category: CATEGORIES[1],
    tags: ['excavación', 'aliviadero', 'obra'],
    associatedFiles: [{ id: 'f8', name: 'video_excavacion.mp4', size: '128 MB', type: 'video' }],
    isImportant: false,
    history: ['2022-12-03T09:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-9',
    name: 'RSA060 - Primer Hormigonado de Fundación',
    description: 'Hito clave: se realiza el primer vertido de hormigón para la base de la presa.',
    occurredAt: '2023-01-22T11:30:00.000Z',
    category: CATEGORIES[1],
    tags: ['hormigón', 'fundación', 'hito'],
    associatedFiles: [{ id: 'f9', name: 'ensayos_hormigon_01.pdf', size: '780 KB', type: 'document' }],
    isImportant: true,
    history: ['2023-01-22T11:30:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-10',
    name: 'RSA060 - Reunión de Avance Mensual',
    description: 'Reunión con contratista para revisar el avance del 25% de la obra.',
    occurredAt: '2023-02-21T10:00:00.000Z',
    category: CATEGORIES[5],
    tags: ['reunión', 'avance', 'seguimiento'],
    associatedFiles: [{ id: 'f10', name: 'minuta_reunion_005.pdf', size: '410 KB', type: 'document' }],
    isImportant: false,
    history: ['2023-02-21T10:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-11',
    name: 'RSA060 - Informe de Monitoreo de Aguas',
    description: 'Resultados del monitoreo de calidad de agua aguas abajo de la zona de obras.',
    occurredAt: '2023-03-23T16:00:00.000Z',
    category: CATEGORIES[2],
    tags: ['agua', 'calidad', 'monitoreo'],
    associatedFiles: [{ id: 'f11', name: 'reporte_calidad_agua.xlsx', size: '1.1 MB', type: 'document' }],
    isImportant: false,
    history: ['2023-03-23T16:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-12',
    name: 'RSA060 - Certificado de Avance de Obra N°5',
    description: 'Emisión del certificado de avance para el pago correspondiente al contratista.',
    occurredAt: '2023-03-28T12:00:00.000Z',
    category: CATEGORIES[3],
    tags: ['certificado', 'pago', 'administración'],
    associatedFiles: [{ id: 'f12', name: 'certificado_avance_005.pdf', size: '2.2 MB', type: 'document' }],
    isImportant: false,
    history: ['2023-03-28T12:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-13',
    name: 'RSA060 - Se alcanza la cota 125m en la presa',
    description: 'La estructura de hormigón principal alcanza la cota de 125 metros sobre el nivel del mar.',
    occurredAt: '2023-05-02T14:00:00.000Z',
    category: CATEGORIES[1],
    tags: ['cota', 'hormigón', 'progreso'],
    associatedFiles: [{ id: 'f13', name: 'registro_topografico_cota125.txt', size: '50 KB', type: 'document' }],
    isImportant: false,
    history: ['2023-05-02T14:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-14',
    name: 'RSA060 - Planos "As-Built" de fundaciones',
    description: 'Recepción de los planos conforme a obra de todas las fundaciones de la estructura.',
    occurredAt: '2023-06-01T17:00:00.000Z',
    category: CATEGORIES[4],
    tags: ['planos', 'as-built', 'documentación'],
    associatedFiles: [{ id: 'f14', name: 'RSA060-AB-FUN-001.pdf', size: '15.3 MB', type: 'document' }],
    isImportant: false,
    history: ['2023-06-01T17:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-15',
    name: 'RSA060 - Auditoría de Seguridad e Higiene',
    description: 'Visita de auditores externos para verificar el cumplimiento de las normas de seguridad.',
    occurredAt: '2023-07-01T10:30:00.000Z',
    category: CATEGORIES[2],
    tags: ['auditoría', 'seguridad', 'informe'],
    associatedFiles: [{ id: 'f15', name: 'informe_auditoria_SyH.pdf', size: '3.1 MB', type: 'document' }],
    isImportant: false,
    history: ['2023-07-01T10:30:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-16',
    name: 'RSA060 - Instalación de compuertas del aliviadero',
    description: 'Comienza el montaje de las grandes compuertas de acero del aliviadero principal.',
    occurredAt: '2023-07-26T09:00:00.000Z',
    category: CATEGORIES[1],
    tags: ['montaje', 'compuertas', 'acero'],
    associatedFiles: [],
    isImportant: true,
    history: ['2023-07-26T09:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-17',
    name: 'RSA060 - Avance de obra del 50%',
    description: 'Hito contractual clave: se certifica que la obra ha alcanzado el 50% de su ejecución física.',
    occurredAt: '2023-08-30T11:00:00.000Z',
    category: CATEGORIES[2],
    tags: ['avance', 'hito', '50%'],
    associatedFiles: [{ id: 'f17', name: 'informe_avance_50.pdf', size: '1.8 MB', type: 'document' }],
    isImportant: true,
    history: ['2023-08-30T11:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-18',
    name: 'RSA060 - Charla con la comunidad local',
    description: 'Reunión informativa con los habitantes de la zona para presentar los avances y resolver dudas.',
    occurredAt: '2023-09-19T18:00:00.000Z',
    category: CATEGORIES[5],
    tags: ['comunidad', 'reunión', 'social'],
    associatedFiles: [{ id: 'f18', name: 'presentacion_comunidad.pptx', size: '4.5 MB', type: 'document' }],
    isImportant: false,
    history: ['2023-09-19T18:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-19',
    name: 'RSA060 - Finalización del cuerpo principal de la presa',
    description: 'Se vierte el último metro cúbico de hormigón en la estructura principal, alcanzando la cota final.',
    occurredAt: '2023-10-20T16:45:00.000Z',
    category: CATEGORIES[1],
    tags: ['finalización', 'hormigón', 'estructura'],
    associatedFiles: [{ id: 'f19', name: 'fotos_cota_final.zip', size: '45 MB', type: 'image' }],
    isImportant: true,
    history: ['2023-10-20T16:45:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-20',
    name: 'RSA060 - Pruebas del sistema de izaje de compuertas',
    description: 'Se realizan las primeras pruebas funcionales de los sistemas mecánicos y eléctricos de las compuertas.',
    occurredAt: '2023-11-20T10:00:00.000Z',
    category: CATEGORIES[1],
    tags: ['pruebas', 'compuertas', 'mecanico'],
    associatedFiles: [{ id: 'f20', name: 'protocolo_prueba_compuertas.pdf', size: '950 KB', type: 'document' }],
    isImportant: false,
    history: ['2023-11-20T10:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-21',
    name: 'RSA060 - Presentación de Plan de Llenado del Embalse',
    description: 'El equipo de ingeniería presenta el plan detallado para el futuro llenado del embalse.',
    occurredAt: '2023-12-20T11:00:00.000Z',
    category: CATEGORIES[0],
    tags: ['plan', 'llenado', 'embalse'],
    associatedFiles: [{ id: 'f21', name: 'plan_llenado_v1.pdf', size: '6.2 MB', type: 'document' }],
    isImportant: false,
    history: ['2023-12-20T11:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-22',
    name: 'RSA060 - Informe de seguimiento arqueológico',
    description: 'Informe final del equipo de arqueología sobre los hallazgos durante las excavaciones.',
    occurredAt: '2024-01-09T14:30:00.000Z',
    category: CATEGORIES[2],
    tags: ['arqueología', 'informe', 'patrimonio'],
    associatedFiles: [],
    isImportant: false,
    history: ['2024-01-09T14:30:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-23',
    name: 'RSA060 - Modificación de Contrato N°2',
    description: 'Se firma una adenda al contrato para ajustar los plazos de finalización de obra.',
    occurredAt: '2024-01-29T12:00:00.000Z',
    category: CATEGORIES[3],
    tags: ['contrato', 'modificación', 'legal'],
    associatedFiles: [{ id: 'f23', name: 'adenda_002.pdf', size: '1.1 MB', type: 'document' }],
    isImportant: false,
    history: ['2024-01-29T12:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-24',
    name: 'RSA060 - Instalación de la instrumentación',
    description: 'Finaliza la instalación de sensores (piezómetros, acelerógrafos) en el cuerpo de la presa.',
    occurredAt: '2024-02-28T16:00:00.000Z',
    category: CATEGORIES[4],
    tags: ['instrumentación', 'sensores', 'monitoreo'],
    associatedFiles: [{ id: 'f24', name: 'plano_instrumentacion.pdf', size: '4.8 MB', type: 'document' }],
    isImportant: false,
    history: ['2024-02-28T16:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-25',
    name: 'RSA060 - Avance de obra 75%',
    description: 'Se certifica que la obra ha alcanzado el 75% de su ejecución física.',
    occurredAt: '2024-03-28T11:30:00.000Z',
    category: CATEGORIES[2],
    tags: ['avance', '75%', 'seguimiento'],
    associatedFiles: [],
    isImportant: false,
    history: ['2024-03-28T11:30:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-26',
    name: 'RSA060 - Revegetación de taludes',
    description: 'Comienzan los trabajos de revegetación en los taludes y áreas afectadas por la obra.',
    occurredAt: '2024-04-17T09:00:00.000Z',
    category: CATEGORIES[1],
    tags: ['ambiental', 'revegetación', 'paisajismo'],
    associatedFiles: [{ id: 'f26', name: 'especificaciones_revegetacion.pdf', size: '2.3 MB', type: 'document' }],
    isImportant: false,
    history: ['2024-04-17T09:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-27',
    name: 'RSA060 - Reunión de Cierre con Contratista',
    description: 'Reunión para definir los detalles de la recepción provisoria de la obra.',
    occurredAt: '2024-05-07T10:00:00.000Z',
    category: CATEGORIES[5],
    tags: ['cierre', 'reunión', 'recepción'],
    associatedFiles: [{ id: 'f27', name: 'minuta_reunion_cierre.pdf', size: '600 KB', type: 'document' }],
    isImportant: false,
    history: ['2024-05-07T10:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-28',
    name: 'RSA060 - Limpieza final del sitio de obra',
    description: 'El contratista realiza la limpieza final de todas las áreas de trabajo y el desmantelamiento del campamento.',
    occurredAt: '2024-05-27T08:30:00.000Z',
    category: CATEGORIES[1],
    tags: ['limpieza', 'finalización', 'ambiental'],
    associatedFiles: [],
    isImportant: false,
    history: ['2024-05-27T08:30:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-29',
    name: 'RSA060 - Plan de capacitación para operación',
    description: 'Documento que detalla la capacitación que recibirá el personal que operará la presa.',
    occurredAt: '2024-06-06T14:00:00.000Z',
    category: CATEGORIES[3],
    tags: ['capacitación', 'operación', 'manual'],
    associatedFiles: [{ id: 'f29', name: 'plan_capacitacion.pdf', size: '890 KB', type: 'document' }],
    isImportant: false,
    history: ['2024-06-06T14:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-30',
    name: 'RSA060 - Entrega de planos "As-Built" finales',
    description: 'El contratista entrega la totalidad de la documentación conforme a obra en formato digital.',
    occurredAt: '2024-06-16T17:00:00.000Z',
    category: CATEGORIES[4],
    tags: ['as-built', 'planos', 'documentación'],
    associatedFiles: [{ id: 'f30', name: 'entrega_final_planos.zip', size: '1.2 GB', type: 'other' }],
    isImportant: true,
    history: ['2024-06-16T17:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-31',
    name: 'RSA060 - Inspección de pre-recepción',
    description: 'Recorrida completa de la obra con el equipo de inspección para generar la lista de observaciones (punch list).',
    occurredAt: '2024-06-26T09:30:00.000Z',
    category: CATEGORIES[1],
    tags: ['inspección', 'recepción', 'punch-list'],
    associatedFiles: [{ id: 'f31', name: 'punch_list_inicial.xlsx', size: '120 KB', type: 'document' }],
    isImportant: false,
    history: ['2024-06-26T09:30:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-32',
    name: 'RSA060 - Informe final de impacto ambiental',
    description: 'Documento consolidado que resume el impacto ambiental real del proyecto y las medidas de mitigación aplicadas.',
    occurredAt: '2024-07-06T11:00:00.000Z',
    category: CATEGORIES[0],
    tags: ['informe', 'eia', 'final'],
    associatedFiles: [{ id: 'f32', name: 'informe_EIA_final.pdf', size: '25.5 MB', type: 'document' }],
    isImportant: false,
    history: ['2024-07-06T11:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-33',
    name: 'RSA060 - Subsanación de observaciones',
    description: 'El contratista informa que ha completado todos los puntos de la "punch list". Se realiza una nueva inspección.',
    occurredAt: '2024-07-16T15:00:00.000Z',
    category: CATEGORIES[1],
    tags: ['inspección', 'observaciones', 'final'],
    associatedFiles: [{ id: 'f33', name: 'cierre_punch_list.pdf', size: '2.1 MB', type: 'document' }],
    isImportant: false,
    history: ['2024-07-16T15:00:00.000Z - Creación de hito de ejemplo.'],
  },
  {
    id: 'sample-34',
    name: 'RSA060 - Acta de Recepción Provisoria de la Obra',
    description: 'Hito final del proyecto. Se firma el acta de recepción provisoria, dando por finalizada la etapa de construcción.',
    occurredAt: '2024-07-21T12:00:00.000Z',
    category: CATEGORIES[3],
    tags: ['acta', 'recepción', 'finalización'],
    associatedFiles: [{ id: 'f34', name: 'acta_recepcion_provisoria.pdf', size: '3.4 MB', type: 'document' }],
    isImportant: true,
    history: ['2024-07-21T12:00:00.000Z - Creación de hito de ejemplo.'],
  },
];
